CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_BME280=y
CONFIG_FPU=y
CONFIG_DEBUG=y
CONFIG_ADXL375=y

# Enable RTC
CONFIG_RTC=y
CONFIG_RTC_STM32=y

# Enable LoRa Driver Subsystem
CONFIG_LORA=y

# Logging Configuration
CONFIG_LOG=y
CONFIG_LORA_LOG_LEVEL_DBG=y

# System / Threading
CONFIG_MAIN_STACK_SIZE=2048